server.port=8080

spring.application.name=api-gateway

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=TokenRelay=

spring.cloud.gateway.routes[1].id=order-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[1].filters[1]=TokenRelay=

spring.security.oauth2.client.provider.keycloak.issuer-uri=http://localhost:8180/realms/diploma-realm

spring.security.oauth2.client.registration.keycloak.client-id=gateway-client
spring.security.oauth2.client.registration.keycloak.client-secret=84jDl4cuGTF5zmasIqN6bp88UkmzGOP9
spring.security.oauth2.client.registration.keycloak.scope=openid,profile,email
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.keycloak.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/diploma-realm

logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.security=DEBUG